@import url("https://fonts.googleapis.com/css?family=Inter:300,regular,500,600,700,800,900&display=swap");@import url("https://fonts.googleapis.com/css2?family=Instrument+Sans:ital,wght@0,400..700;1,400..700&family=Instrument+Serif:ital@0;1&display=swap");* {
	padding: 0rem;
	margin: 0rem;
	border: 0rem;
}
*,
*::before,
*::after {
	box-sizing: border-box;
}
*::before,
*::after {
	display: inline-block;
}
html,
body {
	height: 100%;
}
body {
	line-height: 1;
	scrollbar-gutter: stable;
	-ms-text-size-adjust: 100%;
	-moz-text-size-adjust: 100%;
	-webkit-text-size-adjust: 100%;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
}
input,
button,
textarea {
	font-family: inherit;
	font-size: inherit;
	line-height: inherit;
	color: inherit;
	background-color: transparent;
}
input,
textarea {
	width: 100%;
}
label {
	display: inline-block;
}
button,
select,
option {
	cursor: pointer;
}
a {
	display: inline-block;
	color: inherit;
	text-decoration: none;
}
ul li {
	list-style: none;
}
img {
	max-width: 100%;
	height: auto;
	vertical-align: middle;
}
h1,
h2,
h3,
h4,
h5,
h6 {
	font-weight: inherit;
	font-size: inherit;
}
address {
	font-style: normal;
}

/* Generated by vite-plugin-svg-spritemap */
body {
  min-width: 20rem;
  color: #000;
  font-family: "Inter";
  font-size: 1rem;
}
[data-anim-scrolllock] body {
  overflow: hidden;
  touch-action: none;
  overscroll-behavior: none;
}
.wrapper {
  min-height: 100%;
  display: flex;
  flex-direction: column;
  overflow: clip;
}
.wrapper > main {
  flex: 1 1 auto;
}
.wrapper > * {
  min-width: 0;
}
[class*=__container] {
  max-width: 75rem;
  margin: 0 auto;
  padding-left: 0.9375rem;
  padding-right: 0.9375rem;
}
/* Generated by vite-plugin-svg-spritemap */
:root {
  --base-100: #ebf5df;
  --base-200: #fec81d;
  --base-300: #0f0f0f;
}
img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
h1,
h2 {
  text-transform: uppercase;
  font-family: "Instrument Serif", sans-serif;
  font-weight: 500;
  line-height: 0.9;
}
h1 {
  font-size: clamp(4rem, 7.5vw, 10rem);
}
h2 {
  font-size: clamp(2.5rem, 4.5vw, 5rem);
}
p {
  font-family: "Instrument Sans", sans-serif;
  font-size: 1.125rem;
  font-weight: 400;
}
/* ================= HERO ================= */
.hero {
  position: relative;
  overflow: hidden;
  width: 100%;
  height: 175svh;
  color: var(--base-200);
}
.hero-img {
  position: absolute;
  width: 100%;
  height: 100%;
}
.hero-header {
  position: absolute;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  gap: 0.5rem;
  text-align: center;
  width: 100%;
  height: 100svh;
}
.hero-header p {
  width: 75%;
}
.hero-canvas {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 100%;
  pointer-events: none;
}
.hero-content {
  position: absolute;
  bottom: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  text-align: center;
  width: 100%;
  height: 125svh;
}
.hero-content h2 {
  width: 75%;
  color: var(--base-300);
}
/* ================= ABOUT ================= */
.about {
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100svh;
  background-color: var(--base-300);
  color: var(--base-100);
}
.about p {
  width: 40%;
  text-align: center;
}
/* ================= RESPONSIVE ================= *//* Generated by vite-plugin-svg-spritemap */@media (max-width: 62.5rem){
  .hero-content h2,
  .about p {
    width: calc(100% - 4rem);
  }
}
document.querySelectorAll(".scene-image-wrapper, .scene-image-wrapper-2").forEach((wrapper) => {
  wrapper.style.position = "relative"; 
  const canvas = document.createElement("canvas");
  canvas.className = "hero-canvas";
  canvas.style.position = "absolute";
  canvas.style.bottom = "0";
  canvas.style.left = "0";
  canvas.style.width = "100%";
  canvas.style.height = "100%";
  canvas.style.pointerEvents = "none";
  canvas.style.zIndex = "10";
  wrapper.appendChild(canvas);

  const scene = new Scene();
  const camera = new OrthographicCamera(-1, 1, 1, -1, 0, 1);
  const renderer = new WebGLRenderer({
    canvas,
    alpha: true,
    antialias: false
  });

  const geometry = new PlaneGeometry(2, 2);
  const material = new ShaderMaterial({
    vertexShader,
    fragmentShader,
    uniforms: {
      uProgress: { value: 0 },
      uResolution: { value: new Vector2(wrapper.offsetWidth, wrapper.offsetHeight) },
      uColor: { value: new Vector3(rgb.r, rgb.g, rgb.b) },
      uSpread: { value: CONFIG.spread }
    },
    transparent: true
  });
  
  const mesh = new Mesh(geometry, material);
  scene.add(mesh);

  function resize() {
    const width = wrapper.offsetWidth;
    const height = wrapper.offsetHeight;
    renderer.setSize(width, height);
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    material.uniforms.uResolution.value.set(width, height);
  }

  resize();
  window.addEventListener("resize", resize);

  let scrollProgress = 0;
  function animate() {
    material.uniforms.uProgress.value = scrollProgress;
    renderer.render(scene, camera);
    requestAnimationFrame(animate);
  }
  animate();

  const container = wrapper.closest(".container-scene, .container-scene1, .scene-container2, .scene2, .scene3, .scene4, .scene5, .scene6") || wrapper;

  ScrollTrigger.create({
    trigger: container,
    start: "top top",
    end: "bottom bottom",
    onUpdate: (self) => { scrollProgress = Math.min(self.progress * CONFIG.speed, 1.1); }
  });

  const subtitle = container.querySelector(".scene-subtitle");
  if (subtitle && !subtitle.classList.contains('split-applied')) {
    subtitle.classList.add('split-applied');
    const split = new SplitText(subtitle, { type: "words" });
    const words = split.words;
    gsapWithCSS.set(words, { opacity: 0 });
    
    ScrollTrigger.create({
      trigger: subtitle,
      start: "top 80%",
      end: "bottom 30%",
      onUpdate: (self2) => {
        const progress = self2.progress;
        const totalWords = words.length;
        words.forEach((word, index) => {
          const wordProgress = index / totalWords;
          const nextWordProgress = (index + 1) / totalWords;
          let opacity = 0;
          if (progress >= nextWordProgress) opacity = 1;
          else if (progress >= wordProgress) opacity = (progress - wordProgress) / (nextWordProgress - wordProgress);
          gsapWithCSS.to(word, { opacity: opacity, duration: 0.1, overwrite: true });
        });
      }
    });
  }
});
